repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        pass_filenames: false
        always_run: true

      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --check
        language: system
        pass_filenames: false
        always_run: true

      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        pass_filenames: false
        always_run: true
